### ISSUE TITLE
HTTP API, SDKs and DID Documents (Questions)

### ISSUE THREAD

**Issue by ydennisy** [digitalbazaar/did-client#5]
Hello,

1. I think I saw in the docs that V1 plans to expose a REST style interface for DID creation etc, how far away is this?
2. Do you plan to create this project as an importable SDK for use in node apps?
3. Finally, why is it not possible to generate DID Docs using this client?

Sorry about all the questions!
Thanks.
D

**Comment by dlongley** [comment]
@ydennisy,

> I think I saw in the docs that V1 plans to expose a REST style interface for DID creation etc, how far away is this?

Yes, and this is already functional on the current Veres One test net. Reading and writing to a Veres One ledger node is done through an HTTP API. We're working to clean things up and create better documentation.

As an example, the implementation that will send an "operation" (similar to a "transaction" on bitcoin/ethereum) to a Veres One ledger node is here:

https://github.com/veres-one/did-client-veres-one/blob/implementation/lib/did-client-veres-one.js#L34-L79

This library (did-client) uses the [did-client-veres-one](https://github.com/veres-one/did-client-veres-one) and [did-veres-one](https://github.com/veres-one/did-veres-one) libraries internally.

> Do you plan to create this project as an importable SDK for use in node apps?

This particular project, no, but this project relies upon other libraries including those mentioned above. We also plan on updating our now "ancient" [did-io](https://github.com/digitalbazaar/did-io) library. That library was built against the first DID implementation ever which ran at [authorization.io](https://authorization.io) some years back. That implementation has been made obsolete over time and will be phased out, so the plan is to update the `did-io` library to provide general DID functionality (abstracted in such a way to support Veres One and other DID methods). The Veres One implementation would make use of the aforementioned libraries and provide any other functionality that the `did-client` current provides that should be moved to a library for better reuse in other applications.

`did-client` is intended to be a command line interface for accessing DID features implemented in `did-io` -- making those same features accessible to browser or node apps.

> Finally, why is it not possible to generate DID Docs using this client?

It is! If you're having trouble doing so, please file an issue. See: https://github.com/digitalbazaar/did-client/blob/master/README.md#generate-a-did to generate a DID and corresponding DID Document.

> Sorry about all the questions!

No problem, hopefully I answered sufficiently :).

**Comment by ydennisy** [comment]
Sorry about the delay thanks for your thorough reply @dlongley looking forward to the developments!
