### ISSUE TITLE
Rename to did-cli

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/did-client#7]
Since most of the DID client functionality is being transferred to `did-io` (as of PR https://github.com/digitalbazaar/did-io/pull/12), we should rename this library to `did-cli`.

**Comment by gannan08** [comment]
* [x] Update README.md to reflect the new name `did-cli`
* [x] Update docs.veres.one to link to `did-cli`
* [x] Update npm package to be `did-cli`

**Comment by dmitrizagidulin** [comment]
(The repo itself has been renamed. README and package.json are updated in PR #10.)

**Comment by dmitrizagidulin** [comment]
Done, closing.
